# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20180301_1447'),
        ('music', '0020_album_creator_1'),
    ]

    operations = [
    ]
