# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_merge_20180301_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='creator',
        ),
    ]
