# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0022_remove_album_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_creator',
            new_name='creator',
        ),
    ]
