# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 10:27
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User

def song_creator_fk(apps, schema_editor):
    Song = apps.get_model('music', 'Song')
    for song in Song.objects.all():
        creator = User.objects.get(username = song.creator)
        song.song_creator = creator
        song.save()

    # Song.objects.update(creator2=Subquery(User.objects.filter(username=OuterRef('creator')).only('id')))

class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_song_creator2'),
    ]

    operations = [
    	migrations.RunPython(song_creator_fk, )
    ]
