# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_song_fk_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='creator2',
        ),
        migrations.AlterField(
            model_name='song',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
