# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0026_auto_20180302_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
