# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-02 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0027_auto_20180302_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(max_length=200),
        ),
    ]
