# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0030_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_track',
            field=models.FileField(default=0, upload_to='songs/'),
            preserve_default=False,
        ),
    ]
