# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0031_auto_20180308_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_track',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='songs/'),
        ),
    ]
