# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0032_auto_20180308_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
    ]
