# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 10:28
from __future__ import unicode_literals
# from django.contrib.auth.models import User
from django.db import migrations

def profile_creator(apps, schema_editor):
    profile = apps.get_model('music', 'Profile')
    User = apps.get_model("auth", "User")
    for user in User.objects.all():
        profile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0033_remove_song_audio_file'),
    ]

    operations = [
    	migrations.RunPython(profile_creator, )
    ]