# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0038_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Rock'), (2, 'Hip-hop'), (3, 'Pop'), (4, 'Metal'), (5, 'Jazz')], max_length=5),
        ),
    ]
