# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0039_auto_20180313_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Rock'), (2, 'Hip-hop'), (3, 'Pop'), (4, 'Metal'), (5, 'Jazz')]),
        ),
    ]
