# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-14 11:31
from __future__ import unicode_literals

from django.db import migrations

def artist_fill(apps, schema_editor):
	Album = apps.get_model('music', 'Album')
	Artist = apps.get_model('music', 'Artist')
	for album in Album.objects.all():
		Artist.objects.create(name=album.artist)

class Migration(migrations.Migration):

    dependencies = [
        ('music', '0041_artist'),
    ]

    operations = [
    	migrations.RunPython(artist_fill),
        
    ]