# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-14 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0046_auto_20180314_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Artist'),
        ),
    ]
