# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 10:31
from __future__ import unicode_literals
import random
from django.db import migrations

def song_tempo(apps, schema_editor):
	Song = apps.get_model('music', 'Song')
	for song in Song.objects.all():
		tempo = random.uniform(60.0, 160.0)
		song.tempo = tempo
		song.save()
class Migration(migrations.Migration):

    dependencies = [
        ('music', '0050_song_tempo'),
    ]

    operations = [
    	migrations.RunPython(song_tempo)
    ]
