# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-15 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0052_auto_20180315_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='source_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
